### ISSUE TITLE
No notes pulled from Anki

### ISSUE THREAD

**Issue by doolio** [orgtre/ankiorg#1]
I have this package installed with the following config:

```Emacs-Lisp
(use-package ankiorg
  :straight (:host github :repo "orgtre/ankiorg")
  :after anki-editor)
```
I did not include the `:commands` nor the `:custom` options as per the README as the former is unnecessary as you have an `;;;###autoload` cookie above each of these commands so an autoload will be created automatically for these commands; for the latter I tend not to use the `:custom` keyword but in any case in testing out this package I want to just use it via the AnkiConnect plugin and want to first test pulling notes before pulling media.

When I execute the `ankiorg-pull-notes` command I get prompted to select a deck (the list of available decks is correct) and after doing so I get the following prompt:

> The following changes to deck 'Italian IPA' will be pulled from Anki:
> 
> 0 notes moved to another deck -- to be updated in org.
> 0 notes deleted -- to be deleted in org.
> 0 notes added from another deck -- to be updated in org.
> 0 notes created -- to be created in org.
> 0 notes unchanged in the above ways -- to be updated in org.
> 
> Continue? (y or n)

I presume this is user error on my part. Is there something missing from my configuration required for this to work? Do I perhaps need to set a value for `ankiorg-org-note-file`?

Thanks for your time.

**Comment by orgtre** [comment]
Hi, nice that you're trying this out! You are right about :commands.

I just tested on Anki 2.1.54 and 2.1.60 plus with the latest AnkiConnect from AnkiWeb, and cannot reproduce this. For a deck not already in Org, it should show "x notes created" with x larger than 0 and then import them when pressing "y". No further steps than those you already did should be required.

First: Are you sure that the deck actually contains notes?

What versions of Anki and AnkiConnect are you using?

Can you maybe try with a basic text-only note in a top-level (non-nested) deck without spaces or special characters in the deck name, note type name, field names, etc.? (None of this seems to be a problem for me, but these are the candidates for breakage across versions I can think of right now.)

**Comment by doolio** [comment]
> First: Are you sure that the deck actually contains notes?

Yes, as it is an existing deck in Ankiweb I want to pull into Org, and tweak to make my own.

> I just tested on Anki 2.1.54 and 2.1.60 plus with the latest AnkiConnect from AnkiWeb, and cannot reproduce this.
> What versions of Anki and AnkiConnect are you using?

Apologies, I should have stated this when opening this issue. I'm still on Anki 2.1.15 as that is the latest available on Debian Bullseye. How do I check the AnkiConnect version? I just added it to Anki but it doesn't seem to indicate what version it is. I presume it is the latest one compatible with my version of Anki so I presume a different version to the one you are using.

Reading your README again I see your note that "Not all versions of Anki/Anki-Connect may work.". I presume that it is the issue hear.
